name: QTools
main: com.gmail.leal.mendo.QTools.QTools
version: 1.0
author: agrendath
api-version: 1.21
commands:
  tiago:
    description: Returns useful information about tiago
    usage: /tiago
    permission: quickbarplugin.tiago
    permission-message: You don't have permission to use this extremely powerful command
  qbs:
    description: Gives the player the quickbar switching tool
    usage: /qbs
    permission: quickbarplugin.qbs
    permission-message: You don't have permission for that
  bottles:
    description: Converts xp into xp bottles
    usage: /bottles <amount of bottles>
    permission: quickbarplugin.bottles
    permission-message: You don't have permission for that
  deaths:
    description: Return the amount of deaths for a specific player
    usage: /deaths <playername>
    permission: quickbarplugin.deaths
    permission-message: You don't have permission for that
  apples:
    description: Return the amount of apples eaten for a specific player
    usage: /apples <playername>
    permission: quickbarplugin.apples
    permission-message: You don't have permission for that
  lucas:
    description: Returns useful information about lucas
    usage: /lucas
    permission: quickbarplugin.lucas
    permission-message: You don't have permission to use this extremely powerful command
  souls:
    description: Returns your souls balance or lets you give souls to another player
    usage: /souls give <player> <amount>
    permission: quickbarplugin.souls
    permission-message: You don't have permission to manipulate souls
  soulenchant:
    description: Enchants the item in your hand with a soul enchantment, available enchantments are magnetism and indestructibility
    usage: /soulenchant <enchantment>
    permission: quickbarplugin.soulenchant
    permission-message: You don't have permission to enchant items with souls
  deathstop:
    description: Shows a leaderboard of the top 10 player's deaths
    usage: /deathstop
    permission: quickbarplugin.deathstop
    permission-message: You don't have permission for that
  applestop:
    description: Shows a leaderboard of the top 10 player's apples eaten
    usage: /applestop
    permission: quickbarplugin.applestop
    permission-message: You don't have permission for that
  extract:
    description: Extracts an enchantment from an item and gives it to the player in enchanted book form, does not work for soul enchantments
    usage: /extract <enchantment>
    permission: quickbarplugin.extract
    permission-message: You don't have permission for that